# Generated by Django 4.2.27 on 2026-01-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_title_board_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
