# Generated by Django 4.2.27 on 2026-01-19 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_organizationinvitation'),
        ('projects', '0003_board_is_archived_card_is_archived_list_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BOARD_CREATED', 'Board created'), ('BOARD_ARCHIVED', 'Board archived'), ('BOARD_RESTORED', 'Board restored'), ('LIST_CREATED', 'List created'), ('LIST_REORDERED', 'List reordered'), ('LIST_ARCHIVED', 'List archived'), ('CARD_CREATED', 'Card created'), ('CARD_MOVED', 'Card moved'), ('CARD_REORDERED', 'Card reordered'), ('CARD_ARCHIVED', 'Card archived'), ('CARD_RESTORED', 'Card restored')], max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='projects_ac_organiz_c2b4d7_idx')],
            },
        ),
    ]
