# Generated by Django 4.2.27 on 2026-01-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_activitylog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['title'], name='projects_ca_title_ded40a_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['created_at'], name='projects_ca_created_344d8d_idx'),
        ),
    ]
